### ISSUE TITLE
⚠️ ⚠️ ⚠️  Typescript is disabled in the current implementation ⚠️ ⚠️ ⚠️ 

### ISSUE THREAD

**Issue by riccardo-forina** [patternfly/patternfly-react-seed#132]
We have a bunch of projects based on this, and we just found out that Typescript's type checking is completely disabled across the board.

This means that you can write invalid code like the following and not get a warning when building the project.

```
const foo: string[] = [1, 2, 3]; // <- this shouldn't pass
```

Flipping [this boolean](https://github.com/patternfly/patternfly-react-seed/blob/f865222ca57f42a7e9a90783cbf843186a76d738/webpack.common.js#L19) will properly detect the error and stop the project from being built.

**Comment by mturley** [comment]
I could be wrong but I believe the intention is to check types separately from the build workflow as part of CI (using `tsc --noEmit`, which is available here as `npm run type-check`). That way you can still build and test things mid-development if your types are messed up, but you'll be able to prevent merging PRs with type errors via CI checks.

That said, there's no CI configuration here. It might be a good idea to add an example GitHub Actions workflow to run typechecking/linting/tests.

**Comment by riccardo-forina** [comment]
Yes you are supposed to run that script, but it's not stated anywhere. Given that this project is used by devs from a broad range of expertise, it would
probably be better shipping it with sane defaults. 

For the issue at hand, a simple `prebuild` step could mitigate the problem by enforcing a typecheck at least before building the project for distribution, but I'd argue that having the typecheck run at dev time is of great value.

Honestly, we flipped the boolean I mentioned in our projects and we haven't noticed any worsening of the build's times. It might be different for huge projects, but then would you be using the seed project for that?

**Comment by mturley** [comment]
@riccardo-forina sorry for the delay in returning to this. I have a PR open to address this: https://github.com/patternfly/patternfly-react-seed/pull/147

I tried both approaches (flipping the `transpileOnly` boolean / adding tsc as a prebuild step) and found that `tsc --noEmit` gives a more readable error message when it finds a type error (it's shorter and it shows the offending line with a red underline) than webpack/ts-loader does (it just gives the error message and line number). It's also a little bit faster, but I agree that doesn't really matter much.

Output when encountering a simple type error:

tsc:
```
> patternfly-seed@0.0.2 type-check
> tsc --noEmit

src/app/Support/Support.tsx:21:7 - error TS2322: Type 'number' is not assignable to type 'string'.

21 const foo: string = 3;
         ~~~


Found 1 error.
```

webpack:
```
> patternfly-seed@0.0.2 build
> webpack --config webpack.prod.js && npm run dr:surge

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
assets by status 4.28 MiB [cached] 74 assets
Entrypoint main = main.css main.bundle.js 66 auxiliary assets
orphan modules 2.86 MiB [orphan] 2461 modules
cached modules 904 KiB [cached] 80 modules
runtime modules 1.13 KiB 5 modules
code generated modules 436 KiB (javascript) 223 KiB (css/mini-extract) [code generated]
  cacheable modules 436 KiB
    modules by path ./node_modules/ 247 KiB 43 modules
    modules by path ./src/ 190 KiB
      ./src/index.tsx + 102 modules 183 KiB [built] [code generated]
      ./src/app/bgimages/Patternfly-Logo.svg 7.11 KiB [built] [code generated]
  css modules 223 KiB
    modules by path ./node_modules/@patternfly/react-styles/css/components/ 185 KiB 10 modules
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/@patternfly/react-core/dist/styles/base.css 35 KiB [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./src/app/app.css 343 bytes [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/@patternfly/react-styles/css/utilities/Accessibility/accessibility.css 2.69 KiB [code generated]

ERROR in /Users/mturley/git/patternfly-react-seed/src/app/Support/Support.tsx
./src/app/Support/Support.tsx 21:6-9
[tsl] ERROR in /Users/mturley/git/patternfly-react-seed/src/app/Support/Support.tsx(21,7)
      TS2322: Type 'number' is not assignable to type 'string'.
ts-loader-default_f9e663f8628f9e71
 @ ./src/app/routes.tsx 6:0-47 22:19-26
 @ ./src/app/index.tsx 5:0-40 9:28-37
 @ ./src/index.tsx 3:0-29 17:36-39

webpack 5.72.0 compiled with 1 error in 12885 ms
```

So in the PR I went with the former solution, and left `transpileOnly: true` so we're not running the checker twice on a build. If you think we should flip that boolean anyway just to be safe (if someone runs webpack by hand, for example) I'd be fine with that.
