### ISSUE TITLE
Cannot resolve peer dependencies when running `npm install` without `--legacy-peer-deps`

### ISSUE THREAD

**Issue by javiroman** [patternfly/patternfly-react-seed#134]
```
$ git clone git@gitgit@github.com:patternfly/patternfly-react-seed.git
$ cd patternfly-react-seed
$ rm package-lock.json
$ npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: patternfly-seed@0.0.2
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.5.4 || ^16.0.0" from react-router-last-location@2.0.1
npm ERR! node_modules/react-router-last-location
npm ERR!   react-router-last-location@"^2.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/javiroman/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/javiroman/.npm/_logs/2022-04-04T06_44_47_718Z-debug-0.log

$ npm --version
8.3.1
$ node --version
v16.14.0

```

I'm not sure about the issue, any idea about re-creating the dependency tree when the package-lock.json file is missing?

**Comment by mturley** [comment]
@javiroman sorry to be coming back to this so late. This is happening for me on a regular `npm install` even with the package-lock.json file in place. It appears there is some issue with peer dependencies in this repo when used with newer versions of NPM (v7+) which more strictly enforce peer dependency versions.

The workaround for now is to use `npm install --legacy-peer-deps`, which works correctly (uses the behavior of prior npm versions). What we really need to do is inspect our dependencies and make sure peer dependency versions are aligned so this option is not required. I'll rename this issue to that effect.

**Comment by mturley** [comment]
Looks like we need to wait for another release of `react-router-last-location` before we can fully resolve this. https://github.com/hinok/react-router-last-location/pull/64

**Comment by mturley** [comment]
https://github.com/patternfly/patternfly-react-seed/pull/150 should resolve this, but leaves behind some warnings that I opened https://github.com/patternfly/patternfly-react-seed/issues/151 to track.
