### ISSUE TITLE
Both npm- and yarn-based lockfiles are present, we should choose one

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-react-seed#138]
The repo currently has both `package-lock.json` and `yarn.lock` files present.

Our README uses `npm` commands, so I assume the intention was to switch from yarn to npm. Inspecting the history:
* We started with `yarn.lock` initially
* https://github.com/patternfly/patternfly-react-seed/pull/78 removed `yarn.lock` and switched us to npm's `package-lock.json`
* https://github.com/patternfly/patternfly-react-seed/pull/120 reintroduced `yarn.lock` as a side-effect
* Since then it has only been modified by `dependabot`, where `package-lock.json` has also been modified by hand

So I think we just need to delete `yarn.lock`. I wonder if we should add it to .gitignore?

**Comment by seanforyou23** [comment]
I think yarn.lock was added accidentally, we could just add it to .gitignore?

**Comment by mturley** [comment]
of course I forgot about .gitignore, that's simpler than a pre-commit hook 🤦

**Comment by seanforyou23** [comment]
Cool, I'll send a PR with this and a little other cleanup here in a few.. thx for pointing it out!

**Comment by mturley** [comment]
Oops, sorry @seanforyou23 I opened one too... want me to close it? #139

**Comment by seanforyou23** [comment]
Nah you good! I'll review it
