### ISSUE TITLE
IE Support Investigation

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react-seed#19]
Some customers may find it desirable to support IE11, even though Patternfly does not. Let's take a shot at making this happen to see if it's possible to accomplish without having to touch PF core or react.

- Investigate adding support for auto-prefixer as a post-processing step for our stylesheets so grid and other fancy styling techniques work in IE
- Investigate adding support for <anything that makes it possible> to use css vars in IE

**Comment by dgutride** [comment]
Relates to: https://github.com/patternfly/patternfly-next/issues/450

**Comment by seanforyou23** [comment]
Wanted to share another update before I leave for PTO for rest of year. The latest changes can be seen by pairing the following branch in patternfly-next with the PR that's connected above. We've got the better part of a full page layout going, just trying to work through some issues with grid and some other utility classes. @ibolton336 @dmiller9911 @dgutride 

https://github.com/seanforyou23/patternfly-next/tree/better-css-vars-scoping

<img width="1674" alt="screen shot 2018-12-14 at 3 32 40 pm" src="https://user-images.githubusercontent.com/5942899/50029080-c6909280-ffbf-11e8-9808-f98a1e7f5a95.png">

I will resume this work first of the year unless someone beats me to it :)

**Comment by seanforyou23** [comment]
This issue resulted in the creation of the following guide

https://github.com/patternfly/patternfly-next/wiki/IE11-Support

Using techniques mention there, we were able to achieve the following full page layout.

<img width="1650" alt="screen shot 2019-01-23 at 11 15 08 am" src="https://user-images.githubusercontent.com/5942899/52368745-2b46f700-2a1d-11e9-8b66-42812891d545.png">

Closing this issue, feel free to reopen if I've overlooked anything.
