### ISSUE TITLE
CLI Support

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-react-seed#32]
As a developer, it's a bit cumbersome to consume pf-seed in its current form. People have to clone/fork it, find & replace a bunch of text, likely make other small adjustments to suit their needs.. before you know it what could have been a 1-minute setup turned into, well, something less straight forward.

We'd like to be able to offer some level of automatic configuration that's not possible with a single offering like we have today. For example, the ability to choose between TypeScript and JavaScript as a base language, or a specify a certain type of testing framework.

Something like the angular cli or create-react-app would really help us in both the short and long term. [Yeoman](https://yeoman.io/) has been around for a long time and has quite a community, and gives us the ability to create custom generators. similar to those I mentioned.

Let's give it a try and see what it would take to offer a TypeScript and JavaScript configuration option, as well as exposing options for setting the app name and other simple things that will keep users from having to immediately find & replace upon installing the seed project.

**Comment by thomasmckay** [comment]
Something like https://yeoman.io/ has been useful in other projects.

**Comment by riccardo-forina** [comment]
Maybe rename it `create-patternfly-app’ so one can simply type `yarn create pattern fly-app`? https://yarnpkg.com/lang/en/docs/cli/create/
