### ISSUE TITLE
Background Images don't get displayed.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-react-seed#33]
Tried to add a background image to the project using the instructions found here: 

http://patternfly-react.surge.sh/patternfly-4/components/backgroundimage

Unfortunately it didn't not get displayed, it was just the grey background with no image.  The images where located in /assets/images that I created within the project.

**Comment by seanforyou23** [comment]
@dlabaj I think we can close this one now, feel free to reopen if I've missed something.
