### ISSUE TITLE
404 for bundles when on deep routes

### ISSUE THREAD

**Issue by riccardo-forina** [patternfly/patternfly-react-seed#68]
To reproduce, add a deep route - eg `/some/thing` - and have it served by any sample component. Then hit the refresh button; the app will fail to load because bundles are served from a path that's relative to the current route.

A way to address the issue is to add a `<base href="/">` tag in the header section of the index.html file, but I wonder if that's the best way to do it.

**Comment by seanforyou23** [comment]
Good catch! There definitely should be a `<base>` tag either way, so if it fixes the problem I'd say it's a great first step. I'll send a PR shortly and tag you in it, thanks for reporting this!
