### ISSUE TITLE
Brand and SVG

### ISSUE THREAD

**Issue by karesti** [patternfly/patternfly-react-seed#72]
I don't know if this is the place to ask questions, let me know please where can I join.

I'm building the new Infinispan Console with Patternfly 4 and react, taking this seed as the starting point.
https://github.com/karesti/infinispan-console-ng

I've put under `src/app/assets/images' the images we need to display on the header.

I updated the AppLayout such as 

```javascript
import brand from '@app/assets/images/brand.svg';

const Header = (
    <PageHeader
      logo={<Brand src={brand} alt="Datagrid Management Console"/>}
```

Unfortunately, the svg image does not display. I tested with a png and it works. 
Do I need to add anything else? In the official documentation, the svg seems supported in the brand component.

Thank you!

Katia

**Comment by riccardo-forina** [comment]
Checking the Webpack config, SVG files are importer as raw strings, not as React components. Maybe try this:

```tsx
import brand from '@app/assets/images/brand.svg';

const Logo = () => <div dangerouslySetInnerHTML={{__html: brand}} />;

const Header = (
    <PageHeader
      logo={<Brand src={Logo} alt="Datagrid Management Console"/>}
```

**Comment by karesti** [comment]
@riccardo-forina thanks for the quick reply! It does not seem to work... and I get a typescript message error too. 
maybe we should change the webpack config ?

**Comment by karesti** [comment]
@riccardo-forina btw, displaying the image in a span with the 'dangerouslySetInnerHTML` works

**Comment by riccardo-forina** [comment]
Yes, sorry about that, I didn't notice the `Brand` component. 

I think you can force the SVG to be loaded as a data URL like this:

`import brand from 'url-loader!@app/assets/images/brand.svg';`

then `brand` can be used as the `src` fro the `Brand` component.

**Comment by karesti** [comment]
it still does not work 😢

**Comment by karesti** [comment]
@riccardo-forina I was unable to make it work 😭 
any other idea ?

**Comment by karesti** [comment]
I managed to make it work adding `!!url-loader!@app/assets/images/brand.svg`
