### ISSUE TITLE
Storybook and Babel

### ISSUE THREAD

**Issue by msatkevich** [patternfly/patternfly-react-seed#73]
Hi,

When building, the following warnings appear, followed by a page of related warnings.

warning " > @storybook/react@5.2.1" has unmet peer dependency "@babel/core@^7.0.1".
warning " > @storybook/react@5.2.1" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".

Mike

**Comment by riccardo-forina** [comment]
Those can be ignored since the default webpack settings have been customized so to not use Babel at all
