### ISSUE TITLE
CSS Variable Woes

### ISSUE THREAD

**Issue by c2lknt** [patternfly/patternfly-react-seed#98]
I'm having trouble with the CSS variables.  I'm trying to apply ````{background-position: center;}```` to my ````<BackgroundImage />````, but no luck so far.

I've read about how the variable names are structured, but I'm obviously not doing it correctly (since it's not working!).  I've also done the customization tutorial, but, again, there's some kind of disconnect.

I'm using the ````:root```` pseudoclass per the tutorial, and I've structured the property name based on the names given on [the BackgroundImage component's doc page.](https://www.patternfly.org/v4/documentation/react/components/backgroundimage#css-variables)

````
:root {
    --pf-c-background-image--BackgroundPosition: center;
}
````

It also fails using the css class given in the doc page, eg:

````
.pf-c-background-image {
    background-position: center;
}
````

While help with this particular issue would be lovely, what I'd really like to see would be, in the seed repo, a couple of css variable overrides in the ````app.css```` file, so users can see functional code - preferably in a css property that isn't explicitly given on the documentation pages, so users can see how to construct new ones.

**Comment by seanforyou23** [comment]
Hi @c2lknt! I think the BackgroundImage component is a bit of a special case in terms of styling. I'm not the best person to speak to how the styles for that one specifically can be manipulated, but you should be able to get some help with the specifics of what you're trying to do by raising an issues in the [Patternfly core](https://github.com/patternfly/patternfly) repo.

That said, we did actually have at one point an [example](https://github.com/patternfly/patternfly-react-seed/commit/07ce63048793c2851ffb61c79891d8b8f111f37b#diff-5a536119a315210e992ca583ac6ea2f96193faf04a227c4b3fd65590d9b62743) of setting a custom CSS variable in the standard format in this project. It was a while back and I think that example was just forgotten to be carried over when we added the Page component as chrome for the app here in the seed project. I do agree it would be nice to add this back in some way for illustration purposes. I'll touch base with some of the other devs to see what would be a good example to use. 

In the mean time hopefully the link/example above might be of help and there's also the [katacoda tutorials](https://www.katacoda.com/patternfly/courses/html-css) that may help shed some more light on the subject. Hope it helps.. I'll leave this issue open for now until we get an example in place for ya. Thanks for bringing this up and let me know if this helps or if you have any other questions!
